export default [
  { label: 'Garlic', price: 0.25 },
  { label: 'Broccoli', price: 0.70 },
  { label: 'Cabbage', price: 0.50 },
  { label: 'Cauliflower', price: 0.70 },
  { label: 'Celery', price: 0.40 },
  { label: 'Green Peas', price: 0.40 },
  { label: 'Kale', price: 0.80 },
  { label: 'Spinach', price: 0.70 },
  { label: 'Apples', price: 0.50 },
  { label: 'Lemons', price: 0.60 },
  { label: 'Oranges', price: 0.70 },
  { label: 'Pears', price: 0.60 },
  { label: 'Plums', price: 0.50 },
  { label: 'Raspberries', price: 1.50 },
  { label: 'Strawberries', price: 1.00 },
  { label: 'Bananas', price: 0.20 },
  { label: 'Blueberries', price: 1.50 },
  { label: 'Grapes', price: 0.70 },
  { label: 'Onion', price: 0.30 },
  { label: 'Potato', price: 0.40 },
  { label: 'Tomato', price: 0.50 },
  { label: 'Carrot', price: 0.35 },
];
